name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: Install Dependencies
        run: yarn

      - name: Setup Yarn Workspace
        run: yarn lerna:bootstrap:ci

      - name: Build Packages
        run: yarn build

      - name: Run Linters
        run: yarn lint
        env:
          CI: true

      - name: Run Tests
        run: yarn test:ci
        env:
          CI: true

      - name: Publish
        if: github.event_name == 'push'
        run: yarn lerna:publish:ci
