name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GH_USER: ${{ secrets.GH_USER }}
      GH_REPO: ${{ secrets.GH_REPO }}
      GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
      GIT_NAME: ${{ secrets.GIT_NAME }}

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: Install Dependencies
        run: yarn

      - name: Setup Yarn Workspace
        run: yarn lerna:bootstrap:ci

      - name: Build Packages
        run: yarn build

      - name: Run Linters
        run: yarn lint
        env:
          CI: true

      - name: Run Tests
        run: yarn test:ci
        env:
          CI: true

      - name: Publish
        if: github.event_name == 'push'
        run: |
          git remote set-url origin "https://$GH_USER:$GH_TOKEN@github.com/$GH_REPO.git"
          git config --global user.email "$GIT_EMAIL"
          git config --global user.name "$GIT_NAME"
          npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
          npm whoami
          yarn lerna:publish:ci
